import Head from 'next/head';
import Link from 'next/link';
import { FC } from 'react';
import styled from "styled-components";

const StyledNavBar = styled.div`
display: flex;
align-items: center;
height: 100px;
margin-bottom: 20px;
background-color: #626262;
    a {
        margin: 30px;
        font-size: 22px;
        color: #fff;
        text-decoration: none;
    }
`
interface NavBarProps {
    children: any,
    headTitle?: string,
}

const NavBar:FC<NavBarProps> = ({ children, headTitle = 'CryptoRank' }) => {
    return (
        <>
            <Head>
                <title>{headTitle}</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <StyledNavBar>
                <Link href='/'>Converter</Link>
                <Link href='/currencies'>Cryptocurrency rates</Link>
            </StyledNavBar>
            <div>
                {children}
            </div>
        </>
    )
}

export default NavBar;